sudo: required

language: generic

services:
  - docker

env:
  matrix:
    - PHP_VER=5.6 COMPOSER_VER=1.3.0
    - PHP_VER=5.6 COMPOSER_VER=1.3.1
    - PHP_VER=5.6 COMPOSER_VER=1.3.2
    - PHP_VER=5.6 COMPOSER_VER=1.3.3
    - PHP_VER=5.6 COMPOSER_VER=1.4.0
    - PHP_VER=5.6 COMPOSER_VER=1.4.1
    - PHP_VER=5.6 COMPOSER_VER=1.4.2
    - PHP_VER=7.0 COMPOSER_VER=1.3.0
    - PHP_VER=7.0 COMPOSER_VER=1.3.1
    - PHP_VER=7.0 COMPOSER_VER=1.3.2
    - PHP_VER=7.0 COMPOSER_VER=1.3.3
    - PHP_VER=7.0 COMPOSER_VER=1.4.0
    - PHP_VER=7.0 COMPOSER_VER=1.4.1
    - PHP_VER=7.0 COMPOSER_VER=1.4.2
    - PHP_VER=7.1 COMPOSER_VER=1.3.0
    - PHP_VER=7.1 COMPOSER_VER=1.3.1
    - PHP_VER=7.1 COMPOSER_VER=1.3.2
    - PHP_VER=7.1 COMPOSER_VER=1.3.3
    - PHP_VER=7.1 COMPOSER_VER=1.4.0
    - PHP_VER=7.1 COMPOSER_VER=1.4.1
    - PHP_VER=7.1 COMPOSER_VER=1.4.2
  global:
    # DOCKER_USERNAME
    - secure: Lj8BW5JY/txxcDkjra0/rO2yqxTXYP75VtA+0g2kbHi3V7+EPn2PC+c0G/3dAfjTUnT3PjN4ujOFsxlMql2w+poHS830Y6lWmf/1vIJ0mGdGuJZaI24oGC0suw8HnR+SvpsIvAm53TJ48lZi7FijqQUBYdb6s2L8J2KvNx99foz0p6fWdgTE6pKE6hn9p996BdNBsBMEEDb1cFKn6tNAvr16yovYOT5t0pNtiamci2oyx40VAC4bgq5ft1Cyt43t8Jfc5foXuQWoFC8ZTqOKhAk0pMPHM1p5p/BmRmqwN4JbhYq9Vwb+B62767S2noAhfXYBtbRzXoRm8qLa/ZllKWvnQC7/PKoaioJmNdr6h/1Tn/Tcm1Cxpl3WhjQ8hWsH4HZ8xKM8kRjtgXXfmiSESD7AHKups5+GpHr11uCDmEF2Is0Bi7Mmt96L7GHX/UbHfMBfsb+xnTKRJaKCee/u4qW3Y02RAVWZKMXpxJYZIneRylc9N1qnywEhlIo+V4W4LsM5KmDGkXvaMrVdJwqI47IQpyYs8WEH1duruIB6fM7wry8cNm2yxgmNxHiStbySX0hsT3hKgi9Sv9UuEqea0W+HyXHEF+8ECffnNN9OvYczzOKEXNAEces3DBaihymQkRn+qmAIi4U4IiLjv5uELcVqEsPusNE1Q87C2PdzAzY=
    # DOCKER_PASSWORD
    - secure: U4Q9BYG1Fco0/uPcUxHIRps6gT07sR1t3zt5+wTf4XmROVOaZWHUtTi6WdgiEgXF0n5TuzN/Vs9QYc4jkvU8r5pV7v6rBLKNtH4jUIidR537SzeffoShXnIPX/XHhb09eobk8Sb/fq5GbZidqsHk5IZlJv60qxvqigJ/m1RrgR6ol74v92WsHrOAB9W+d4LzcD58Uj0YCCW0TOyiWph7B+G8M4ecHRWY/sCEAIAMYcpbQ6LbqsLGe36KH2rctbT+D15qjmuDgj9xN3++F+E9seB6UY4rWQBYH64hC5d8WjqHPhksBZORCj3WFtiKwwBodLLsKvbfMIwTfkpWw2GUS7KIU48TWGEh70qs/LQY+CEV1eFiNenUQ4qik3BAI7GYrrIHZSigqxg2NbVaqdm5Dm3gyc32ANffvnDboQqyX8J4R61rC1no5G7+85plV8LKLszx/ykCh4kf0Lqh4LM+O9pYp6V6bE+hnWE53RhMNo88d1ypnG5Ha0mekfM8qkborytKmJijTjjCCsQ28R2jrJcQqJ3Gt7mskrmSw7TZcKIZrgX+nd7qiY7E4RqHp+uSloDg7DohhKj44jzRYcN4blrA0y/jpeWmSinpK0EDYgdURD94uvWsr93kzGFsGrE+i8x2WpzuATsLPn5jiCCUtFqgJdsCNiDTKs80MRZlDsY=
script:
  - make build
  - make test

deploy:
  - provider: script
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make deploy
    on:
      branch: master

matrix:
  fast_finish: true
